"""Add 'embed' column to 'Post' model.

Revision ID: 368db99edeb
Revises: 573d7be4f8b
Create Date: 2015-08-29 11:26:00.578960

"""

# revision identifiers, used by Alembic.
revision = '368db99edeb'
down_revision = '573d7be4f8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('embed', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'embed')
    ### end Alembic commands ###
