"""Add SocialIcon

Revision ID: 573d7be4f8b
Revises: 26736215c10
Create Date: 2015-08-29 09:41:04.005242

"""

# revision identifiers, used by Alembic.
revision = '573d7be4f8b'
down_revision = '26736215c10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_icons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(length=140), nullable=True),
    sa.Column('css_value', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_icons')
    ### end Alembic commands ###
